import { colors, radius } from './src/styles/tokens';

/**
 * Chest-shake keyframes (`ui-spec.md` §6).
 *
 * The chest alternates direction `CHEST_SHAKE_STEPS` times per cycle, so a
 * stronger shake is both bigger **and** more frantic. Each tier repeats the
 * cycle (`animationIterationCount`, set inline) for longer, so later shakes
 * rattle for more cycles as well as harder. Amplitude is driven by the
 * `--chest-shake-{x,y,rot,scale}` CSS variables (set inline from completion
 * progress); the fallbacks are the spec's baseline wobble.
 */
const CHEST_SHAKE_STEPS = 9;
const chestShakeKeyframes = Object.fromEntries(
  Array.from({ length: CHEST_SHAKE_STEPS + 1 }, (_, i) => {
    const pct = `${Math.round((i / CHEST_SHAKE_STEPS) * 100)}%`;
    if (i === 0 || i === CHEST_SHAKE_STEPS) {
      return [pct, { transform: 'translate(0, 0) rotate(0deg) scale(1)' }];
    }
    const dir = i % 2 === 1 ? -1 : 1;
    const scale = i % 2 === 1 ? 'var(--chest-shake-scale, 1)' : '1';
    return [
      pct,
      {
        transform:
          `translate(calc(${dir} * var(--chest-shake-x, 2px)), calc(${-dir} * var(--chest-shake-y, 0.5px))) ` +
          `rotate(calc(${dir} * var(--chest-shake-rot, 2deg))) scale(${scale})`,
      },
    ];
  }),
);

/**
 * Tailwind CSS configuration — TechFair Mission Tracker.
 *
 * Tailwind v4 (`@tailwindcss/vite`) is CSS-first and no longer auto-discovers a
 * JavaScript config, so this file is loaded explicitly from
 * `src/styles/global.css` via the `@config` directive.
 *
 * `theme.extend.colors` (rather than `theme.colors`) preserves the full default
 * palette and only pins the mission-tracker roles. Raw values live in
 * `src/styles/tokens.ts` and are imported here so utilities and runtime JS share
 * one source of truth (Tailwind loads this file through `jiti`, which resolves
 * the TS import).
 *
 * Palette v2 (`ui-spec.md` §1.2): all mission-tracker colors live under the
 * `brand-*` namespace. The v1 `teal-*`, `emerald-*` and `slate-*` overrides are
 * removed — use `brand-*` everywhere.
 *
 * @type {import('tailwindcss').Config}
 */
export default {
  theme: {
    extend: {
      borderRadius: {
        /**
         * Top-panel radius. The default scale caps at `rounded-3xl` (1.5rem),
         * while `ui-spec.md` §1.2 / the layout skeleton call for a 2.5rem top
         * panel (`rounded-t-panel`) that tucks under the hero zone.
         */
        panel: radius.panel,
      },
      /**
       * Rapid vibration applied to the closed chest for 500ms when a non-final
       * mission is completed (`ui-spec.md` §6). Generated by
       * `chestShakeKeyframes` above; amplitude comes from the
       * `--chest-shake-*` variables so it scales with progress.
       */
      keyframes: {
        'chest-shake': chestShakeKeyframes,
        /**
         * Overshoot-then-settle scale for the permanent chest-open swap when all
         * missions are completed (`ui-spec.md` §6). Runs once for ~400ms.
         */
        'pop-in': {
          '0%': { transform: 'scale(0.7)' },
          '60%': { transform: 'scale(1.05)' },
          '100%': { transform: 'scale(1)' },
        },
      },
      animation: {
        // `linear` keeps every direction change sharp instead of easing each
        // swing, which reads as a much more violent rattle.
        'chest-shake': 'chest-shake 0.5s linear',
        'pop-in': 'pop-in 0.4s ease-out',
      },
      colors: {
        /** Approved v2 brand palette — the only UI colors (`ui-spec.md` §1.2). */
        brand: {
          /** Page/app background. */
          bg: colors.bg,
          /** High-emphasis text. */
          ink: colors.ink,
          /** Muted/supporting text. */
          muted: colors.muted,
          /** Primary interactive accent (active states, fills). */
          accent: colors.accent,
          /** Unfilled tracks / soft highlight backgrounds. */
          track: colors.track,
          /** Dark surfaces (icon tiles) / high-contrast accent. */
          deep: colors.deep,
          /** Card/surface background. */
          white: colors.white,
          /** Reserved: alerts / warning / attention states. */
          orange: colors.orange,
          /** Reserved: soft warning background. */
          'orange-soft': colors.orangeSoft,
        },
      },
    },
  },
};
